version: "3.5"

services:
  receiver:
    tty: true
    build: ./receive
    restart: always
    links:
      - rabbit
      - database
  rabbit:
    tty: true
    build: ./rabbit
    ports:
      - 5672:5672
      - 15672:15672
  database:
    tty: true
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
